on:
  pull_request:
  workflow_dispatch:

name: Lint

jobs:
  pentest:
    name: Execute program
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.1.1

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: pypy-3.7

    - name: Execute
      run: |
        ls -la .
